config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  get 'get-started', to: 'splash#index'

  devise_for :users

  resources :categories, only: %i[create new] do
    resources :entities, only: %i[new create index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :category
  belongs_to :entity
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :categorizations
  has_many :entities, through: :categorizations

  validates :name, presence: true, length: { minimum: 3 }
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :categorizations
  has_many :categories, through: :categorizations

  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :entities, foreign_key: 'author_id'
  has_many :categories, foreign_key: 'author_id'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  validates :name, presence: true, length: { minimum: 3 }
  validates_presence_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :load_directives
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def load_directives
    @app_title = ENV.fetch('BUDGET_APP_TITLE', 'BudgetApp')
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end

  def authenticate_user!
    return super if user_signed_in? || devise_controller?

    redirect_to(get_started_path)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category
      .select('categories.*, SUM(T.amount) as amount')
      .joins('LEFT JOIN categorizations as C ON C.category_id = categories.id')
      .joins('LEFT JOIN entities as T ON T.id = C.entity_id')
      .where(author: current_user)
      .group(:id)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(create_params)
    if @category.save
      redirect_to(root_path, notice: 'Category created successfully!')
    else
      render(
        :new,
        status: :unprocessable_entity,
        alert: @category.errors.objects.first.full_message
      )
    end
  end

  private

  def create_params
    params
      .require(:category)
      .permit(:name, :icon)
      .merge(author: current_user)
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @entities = @category.entities.order(created_at: :desc)
    @amount = @entities.sum(:amount)
  end

  def new
    if Category.where(author: current_user).ids.empty?
      redirect_to(
        new_category_path,
        notice: "Can't create transactions without categories"
      ) and return
    end

    @entity = Entity.new
    category_id = params[:category_id]
    render(:new, locals: { category_id:, my_categories: helpers.my_categories_except(category_id) })
  end

  def create
    categ_ids = params.require(:entity).fetch(:category_ids, [])[1..]
    categ_ids << params[:category_id]

    @entity = Entity.new(create_params)
    return error_render(@entity.errors.objects.first.full_message) unless @entity.save

    @entity.categories.push(*Category.where(id: categ_ids))
    redirect_to(
      category_entities_path(params[:category_id]), notice: 'Transaction created successfully!'
    )
  end

  private

  def create_params
    params
      .require(:entity)
      .permit(:name, :amount)
      .merge(author: current_user)
  end

  def transaction_params
    params.permit(:category_id).merge(entity: @entity)
  end

  def error_render(error)
    flash.now[:alert] = error
    render(:new, status: :unprocessable_entity)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    return redirect_to(root_path) if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def created_by
    render(inline: "Creator: <strong>#{current_user.name}</strong>")
  end

  def total_amount(model)
    render(inline: "Total amount: <strong><i>$</i>#{model.amount || 0}</strong>")
  end

  def get_icon(icon)
    icon.strip == '' ? 'categ.png' : icon
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
  def my_categories_except(category_id)
    Category.where('author_id = ? AND id <> ?', current_user.id, category_id)
  end

  def humanize_date(entity)
    entity.created_at.strftime('%m-%d-%Y')
  end
end

app/views/categories/_category.html.erb
<li class="categ-item ft-item">
  <%= image_tag(get_icon(category.icon)) %>
  <div>
    <%= link_to(category.name, category_entities_path(category)) %>
    <div class="flex-between">
      <span><%= created_by %></span>
      <span><%= total_amount(category) %></span>
    </div>
  </div>
</li>

app/views/categories/index.html.erb
<% content_for(:stylesheets) do %>
  <%= stylesheet_link_tag('categories/index') %>
<% end %>

<%= render('shared/navs/main', title: 'CATEGORIES', load_more: nil) %>

<section class="flex-col ft-sec ft-categ">
  <% if @categories.empty? %>
    <%= render('shared/empty_list') %>
  <% else %>
    <ul class="flex-col" id="catego_list">
      <%= render(@categories) %>
    </ul>
  <% end %>
</section>

<%= link_to('New Category', new_category_path, class: 'new-ft-btn') %>

app/views/categories/new.html.erb
<%= render('shared/form', title: 'NEW CATEGORY', action: 'Create', url_to: root_path) %>

<section>
  <%= form_with(model: @category, html: { class: 'flex-col devise-form', id: 'devise_user' }) do |f| %>
    <%= f.text_field(:name, class:'field', placeholder: 'Name', required: true) %>
    <span class="spacer"></span>
    <%= f.text_field(:icon, class: 'field', placeholder: 'Icon', required: true) %>
  <% end %>
</section>

app/views/entities/_entity.html.erb
<li class="trans-item ft-item">
  <h4 class="flex-between">
    <span><%= entity.name %></span>
    <strong><i>$</i><%= entity.amount %></strong>
  </h4>
  <p><%= humanize_date(entity) %>
</li>

app/views/entities/index.html.erb
<%= render('shared/navs/main', title: 'TRANSACTIONS', load_more: true) %>

<section class="flex-col ft-sec ft-trans">
  <h3 class="flex-between">
    <%= render('shared/buttons/back', url: root_path) %>
    <span><%= @category.name %></span>
    <span><i>$</i><%= @amount || 0 %></strong></span>
  </h3>

  <% if @entities.empty? %>
    <%= render('shared/empty_list') %>
  <% else %>
    <ul class="flex-col" id="trans_list">
      <%= render(@entities) %>
    </ul>
  <% end %>
</section>

<%= link_to('New Transaction', new_category_entity_path, class: 'new-ft-btn') %>

app/views/entities/new.html.erb
<%= render('shared/form', title: 'NEW TRANSACTION', action: 'Create', url_to: category_entities_path(category_id)) %>

<section class="new-ft-trans">
  <%= form_with(model: @entity, url: category_entities_path(category_id), class: 'flex-col devise-form', id: 'devise_user') do |f| %>
    <%= f.text_field(:name, class: 'field', placeholder: 'name', required: true) %>
    <span class="spacer"></span>
    <%= f.number_field(:amount, class: 'field', placeholder: 'amount', min: 0, required: true) %>

    <div class="categs-list">
      <%= f.label('Other Categories (Optional)') %>
      <%= f.collection_check_boxes(:category_ids, my_categories, :id, :name) do |b| %>
        <div>
          <%= b.check_box %>
          <%= b.label %>
        </div>
      <% end %>
    </div>
  <% end %>
</section>

app/views/home/splash.html.erb
<section>
  <h2><%= @app_name %></h2>

  <%= link_to('LOG IN', new_user_session_path) %>

  <%= link_to('SIGN UP', new_user_registration_path) %>
<section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @app_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.2.0/css/all.css">
    <link rel="stylesheet" href="https://use.typekit.net/emv3zbo.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.digital.arizona.edu/lib/arizona-bootstrap/2.0.18/css/arizona-bootstrap.min.css" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= yield(:stylesheets) %>
    <%= javascript_importmap_tags %>
    <%= yield(:scripts) %>
  </head>

  <body>
    <main>
      <%= render('shared/flash') %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/flash.html.erb
<% if msg = flash[:notice] %>
  <div class="flash flash-notice"><%= msg %></div>
<% elsif msg = flash[:alert] %>
  <div class="flash flash-alert"><%= msg %></div>
<% end %>

app/views/shared/_empty_list.html.erb
<p class="empty-list">No records found</p>

app/views/shared/_flash.html.erb
<% if msg = flash[:notice] %>
  <div class="flash flash-notice"><%= msg %></div>
<% elsif msg = flash[:alert] %>
  <div class="flash flash-alert"><%= msg %></div>
<% end %>

app/views/shared/_form.html.erb
<% content_for(:stylesheets) do %>
  <%= stylesheet_link_tag('shared/any-form') %>
<% end %>

<%= render('shared/navs/primitive', title:, action:, url_to:) %>

app/views/shared/buttons/_back.html.erb
<% content_for(:stylesheets) do %>
  <%= stylesheet_link_tag('shared/buttons') %>
<% end %>

<%= link_to(url, class: 'back-btn') do %>
  <i class="fa-solid fa-arrow-left"></i>
<% end %>

app/views/shared/navs/_main.html.erb
<% content_for(:stylesheets) do %>
  <%= stylesheet_link_tag('shared/top-nav') %>
  <%= stylesheet_link_tag('shared/buttons') %>
<% end %>

<nav class="top-nav" data-controller="navs">
  <ul class="flex-between">
    <li>
      <button class="options-btn" data-action="click->navs#toggle">
        <i class="fa-solid fa-bars"></i>
        <%= render('shared/navs/side') %>
      </button>
    </li>
    <li>
      <h2><%= title %></h2>
    </li>
    <li>
      <button class="search-btn" data-action="click->navs#toggleSearch"><i class="fa-solid fa-magnifying-glass"></i></button>
    </li>
  </ul>

  <input type="hidden" data-navs-target="for_list" value="<%= load_more %>">

  <% if load_more %>
    <div class="trans-more">
      <button type="button" class="filter-btn filter-on" data-navs-target="desc" data-action="click->navs#descend">Most recent</button>
      <button type="button" class="filter-btn" data-navs-target="asc" data-action="click->navs#ascend">Most ancient</button>
    </div>
  <% end %>

  <div class="flex-center search-wrapper hidden" data-navs-target="finder">
    <input type="text" class="field" data-navs-target="keyword" data-action="change->navs#reset" placeholder="Search keyword">
    <button type="button" data-action="click->navs#lookup"><i class="fa-solid fa-magnifying-glass"></i></button>
  </div>
</nav>

app/views/shared/navs/_primitive.html.erb
<% content_for(:stylesheets) do %>
  <%= stylesheet_link_tag('shared/top-nav') %>
<% end %>

<nav class="flex-between top-nav">
  <%= render('shared/buttons/back', url: url_to || get_started_path) %>

  <h2><%= title %></h2>
  <button type="submit" form="devise_user"><%= action %></button>
</nav>

app/views/shared/navs/_side.html.erb
<% content_for(:stylesheets) do %>
  <%= stylesheet_link_tag('shared/side_nav') %>
<% end %>

<div class="side-nav hidden" data-navs-target="side_nav">
  <div class="flex-col">
    <%= link_to('Logout', destroy_user_session_path, data: { turbo_method: :delete }) %>
  </div>
</div>

app/views/splash/index.html.erb
<% content_for(:stylesheets) do %>
  <%= stylesheet_link_tag('splash') %>
<% end %>

<section class="flex-col splash">
  <h2 class="flex-center title">
    <span><%= @app_title %></span>
  </h2>

  <%= link_to('LOG IN', new_user_session_path, class: 'splash-login') %>

  <%= link_to('SIGN UP', new_user_registration_path) %>
<section>